name: mobilepay_flutter
description: A Flutter plugin for MobilePay Appswitch for DK
version: 1.0.0
homepage: https://github.com/AndreasLyngholm/mobilepay_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: simpleconcept.dk.mobilepay_flutter
        pluginClass: MobilePayFlutterPlugin
      ios:
        pluginClass: MobilePayFlutterPlugin